
#ifndef Certificate_H
#define Certificate_H

// this is a2n Tech CA certificate
static const char CA_CERT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIUf6pWvYlFX/l1c79tHYmMe2AYXX0wDQYJKoZIhvcNAQEL
BQAwEzERMA8GA1UEAwwIYTJuIFRlY2gwIBcNMjQwMjExMDgwNzQ5WhgPMjA1MDAy
MTQwODA3NDlaMBMxETAPBgNVBAMMCGEybiBUZWNoMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAqMMiK7Hgm9tU4L2r+Ur0UUJmNTjWvfS0f36ZDDbWd1Kv
VMCEUwkTbjMfOUfHbPLpLrjbs6WusnEnwWZFWGRZF0BAMOlqLIqWQuWPUf7nhCKh
BYb6RzmXakkMGT9Mhfn0RpFH4yQB4INMVvYACiAVlO59xZ6q4u7HEkiZfL1l1IdM
dJUjKxl2hei99HxJDezPTgE7QCAGUYiCz2sUqfRHwUTKtyFcOAqb95T6JAuJhDJa
gxv9+DjW1fMnhjW6dxjmhNQ8TKEKW62u+qD2nys36xwM6fRYJKeOYl1wuaxTepeg
suJ4LdKCRk5YhfiuDLDkAKk4kcn3AM6W7aJx+jbvNQIDAQABo1MwUTAdBgNVHQ4E
FgQUQbVGHk/F8ziS6DxuUFrsqfD4C9IwHwYDVR0jBBgwFoAUQbVGHk/F8ziS6Dxu
UFrsqfD4C9IwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAIYGQ
eZZr5124RFgELs2x2ig+kqJ51+TYeoOnGPvHFccoFSF/3o8zLhuBRbjSkHb5J6mt
2qHfuQ7y8L9TYWLGpZkJWc4H8jkSMpVWFqqQwycoPjyPQrYt2Z07V8Vdke5eTYBc
3qJqAHf3aux8spfwmfLf6GCG3mkljLTxfcjK5R0CIMoVNKfjjVqLmBP0952GcqYf
MOzCNz5rmxBXbehlQ9rwY1nhy2+OC7lmDZOBj9D2ubM7+/C0WRIxhOUlsZ+vSLpq
8mYmu7d/pquWTDAzBWlPAdg3KQKU9DZTbK7E8W7EXXPe0kWLS8mzjuSAVm/sKZSx
13apL/CbgdITkwtvjA==
-----END CERTIFICATE-----
)KEY";

static const char DEVICE_CERT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
YOUR CLIENT CERTIFICATE HERE (base64 encoded format)
-----END CERTIFICATE-----
)KEY";

static const char DEVICE_KEY[] PROGMEM = R"KEY(
-----BEGIN PRIVATE KEY-----
YOUR PRIVATE KEY HERE (base64 encoded format)
-----END PRIVATE KEY-----
)KEY";

#endif